require("color.bamboo")
require("color.evangelion")
require("color.kanagawa")
require("color.lemon")
require("color.neovim_ayu")
require("color.nightfly")
require("color.onedark")
require("color.tokyonight")
require("color.pastel")
require("color.cyberdream")
-- Load the plugin before last-color may recall it, then make Omarchy authoritative.
local omarchy = require("color.omarchy")
require("color.last")
omarchy.apply()
