return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  config = function()
    local nvim_treesitter = require("nvim-treesitter.configs")

    nvim_treesitter.setup({
      ensure_installed = {
        "awk",
        "bash",
        "bibtex",
        "c",
        "cmake",
        "cpp",
        "css",
        "csv",
        "dart",
        "diff",
        "dockerfile",
        "git_config",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitcommit",
        "gitignore",
        "gitignore",
        "gnuplot",
        "gnuplot",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "gpg",
        "graphql",
        "groovy",
        "helm",
        "helm",
        "html",
        "http",
        "hurl",
        "ini",
        "java",
        "javadoc",
        "javascript",
        "jinja",
        "jinja_inline",
        "jq",
        "json",
        "json5",
        "julia",
        "kotlin",
        "kulala_http",
        "latex",
        "lua",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "muttrc",
        "php",
        "po",
        "promql",
        "pug",
        "python",
        "readline",
        "readline",
        "regex",
        "ruby",
        "rust",
        "sql",
        "ssh_config",
        "swift",
        "terraform",
        "terraform",
        "tmux",
        "tmux",
        "toml",
        "toml",
        "tsv",
        "typescript",
        "typst",
        "typst",
        "vala",
        "vim",
        "vim",
        "vimdoc",
        "vimdoc",
        "vue",
        "vue",
        "xml",
        "yaml",
        "zathurarc",
      },
      sync_install = false,
      auto_install = true,
      ignore_install = {},
      highlight = {
        enable = true,
        disable = {},
        additional_vim_regex_highlighting = false,
      },
      modules = {},
    })
  end,
}
